Dmalkr/vector prop tests
Shimuuar/vecvec pull request #1
Opened 2023-05-09 12:37 UTC by dmalkr

2023-05-09 13:06 UTC, Shimuuar requested changes
Great! Thanks

There's quite a bit of orphans we don't need: all arbitrary instances for vectors from `vector`. Please kill unused ones and move remaining ones into `TST.Orphanage`. And drop `-fno-orphans` from cabal file

Please also make code warning free. `TST.Property` has tons of top-level functions without signature so just drop `{-# OPTIONS_GHC -Wno-missing-signatures #-}` there

2023-05-09 13:06 UTC, Shimuuar commented on vecvec-lapack/vecvec-lapack.cabal
> +                  TypeFamilies
Please enable CPP & TH on per module basis

2023-05-09 13:11 UTC, Shimuuar commented
Oh! Another thing. Please add possibility to generate vectors with non-1 stride in Arbitrary for Vec. See following as an example:

https://github.com/Shimuuar/vecvec/blob/7d73f0498328fad5a63f88762ef478feac179354/vecvec-lapack/tests/TST/Model.hs#L345-L348

2023-05-14 10:34 UTC, dmalkr commented on vecvec-lapack/vecvec-lapack.cabal
> +                  TypeFamilies
CPP & TH moved to modules.

2023-05-24 04:18 UTC, dmalkr commented
> Oh! Another thing. Please add possibility to generate vectors with non-1 stride in Arbitrary for Vec. See following as an example:
> 
> https://github.com/Shimuuar/vecvec/blob/7d73f0498328fad5a63f88762ef478feac179354/vecvec-lapack/tests/TST/Model.hs#L345-L348

2023-05-24 04:21 UTC, dmalkr commented
Oh, got confused in the comment interface and accidentally closed the PR. :(

2023-05-24 04:38 UTC, dmalkr commented
> Oh! Another thing. Please add possibility to generate vectors with non-1 stride in Arbitrary for Vec. See following as an example:
> 
> https://github.com/Shimuuar/vecvec/blob/7d73f0498328fad5a63f88762ef478feac179354/vecvec-lapack/tests/TST/Model.hs#L345-L348

Done for `Arbitrary`. `TestData` also need to make `Vec`s from lists, but it have no access to random generating. So I made here fixed stride:



Oh! Another thing. Please add possibility to generate vectors with non-1 stride in Arbitrary for Vec. See following as an example:

https://github.com/Shimuuar/vecvec/blob/e0fe928708bfa55e1f96a6a60ad8a2f7ab5b7963/vecvec-lapack/tests/Utilities.hs#L114-L120

2023-05-24 05:03 UTC, dmalkr commented on vecvec-lapack/vecvec-lapack.cabal
> +                  TypeFamilies
Both files, `Utilities.hs` and `TST/Property.hs` are copied from `vector`. And we hope tests from `vector` will be separated into other package. So we can just import them. So I didn't move any orphans, and just silent such warnings.

2023-05-28 16:14 UTC, merged